### PR TITLE
feature: support using different ApolloProviders

### PR DESCRIPTION
**Pull request by sarfata**
This is useful if you are using react-apollo-hooks.

### CODE REVIEW

**Comment by benawad** [comment]
I just merged https://github.com/benawad/apollo-mocked-provider/pull/3 I'm happy to merge this after conflicts are resolved.

**Comment by sarfata** [comment]
I resolved the conflict but now that the second argument (`globalCache`) is optional, it's a bit weird to pass the provider as the third argument (you have to pass `undefined` as first argument):

```tsx
export const ApolloMockedProvider = createApolloMockedProvider(
  typeDefs,
  undefined,
  ApolloProvider
);
```

Maybe we should switch to an options argument shared by all three functions that could accept a cache and/or a provider? Would you agree to this? I can do the change if we agree.

**Comment by benawad** [comment]
Yeah let's do an options argument

**Comment by sarfata** [comment]
Ok should be good now. Sorry about all the commits. This definitely deserves a squash when merging.

**Pull request merged**
